FROM node:22-bookworm-slim

WORKDIR /app

ENV PUPPETEER_SKIP_DOWNLOAD=true

COPY package*.json ./
RUN npm ci

COPY server.js ./
COPY src ./src
COPY uploads ./uploads

EXPOSE 3001

CMD ["npm", "start"]
