const { z } = require('zod');
const { getAccessContext } = require('../services/accessContext');
const { getEducationServices } = require('../services/education');
const { educationError } = require('../services/education/EducationAccessService');

const uuid = z.string().uuid();
const nullableUuid = uuid.optional().nullable();
const json = z.record(z.any());
const workspaceCreate = z.object({
  workspaceType: z.enum(['STUDENT','ACADEMIC','COURSE','RESEARCH_PROJECT']), organizationId: nullableUuid,
  title: z.string().trim().min(1).max(255), description: z.string().max(10000).optional().nullable(),
  legalDomain: z.string().max(120).optional().nullable(),
  academicLevel: z.enum(['UNDERGRADUATE','GRADUATE','DOCTORAL','PROFESSIONAL','OTHER']).optional().nullable(),
}).strict();
const workspacePatch = workspaceCreate.omit({ workspaceType: true, organizationId: true }).partial().extend({ status: z.enum(['ACTIVE','ARCHIVED']).optional() }).strict();
const topicSchema = z.object({ courseId: nullableUuid, parentTopicId: nullableUuid, title: z.string().trim().min(1).max(255), description: z.string().max(10000).optional().nullable(), sortOrder: z.number().int().min(0).max(100000).optional() }).strict();
const noteCreate = z.object({ topicId: nullableUuid, title: z.string().trim().min(1).max(255), contentJson: json.optional(), plainText: z.string().max(200000).optional(), status: z.enum(['DRAFT','ACTIVE','ARCHIVED']).optional() }).strict();
const notePatch = z.object({ title: z.string().trim().min(1).max(255).optional(), contentJson: json.optional(), plainText: z.string().max(200000).optional(), status: z.enum(['DRAFT','ACTIVE','ARCHIVED']).optional(), changeSummary: z.string().max(500).optional().nullable(), suggestionId: nullableUuid }).strict();
const noteSuggestion = z.object({ operation: z.enum(['SUMMARIZE','SIMPLIFY','EXAMPLE','COMPARE','FLASHCARDS','QUIZ']), sourceIds: z.array(uuid).max(50).optional() }).strict();
const citation = z.object({ field: z.enum(['facts','legalIssue','holding','reasoning','dissent','significance']), sourceId: uuid, chunkId: uuid, excerpt: z.string().min(1).max(20000) }).strict();
const briefCreate = z.object({ legalSourceId: uuid, chunkId: nullableUuid, title: z.string().trim().max(500).optional(), caseNumber: z.string().max(100).optional(), decisionNumber: z.string().max(100).optional() }).strict();
const briefPatch = z.object({ facts: z.string().max(100000).optional().nullable(), legalIssue: z.string().max(100000).optional().nullable(), holding: z.string().max(100000).optional().nullable(), reasoning: z.string().max(100000).optional().nullable(), dissent: z.string().max(100000).optional().nullable(), significance: z.string().max(100000).optional().nullable(), citations: z.array(citation).max(100).optional(), acceptSuggestion: z.boolean().optional() }).strict();
const flashcardSchema = z.object({ topicId: nullableUuid, topic: z.string().max(500).optional(), count: z.number().int().min(1).max(50).optional(), sourceIds: z.array(uuid).min(1).max(50) }).strict();
const questionSchema = z.object({ questionType: z.enum(['MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER','ISSUE_SPOTTING','CASE_ANALYSIS']), prompt: z.string().min(1).max(20000), options: z.array(z.any()).max(20).optional().nullable(), answerSchema: json, explanation: z.string().min(1).max(20000), sourceIds: z.array(uuid).min(1).max(20), difficulty: z.enum(['EASY','MEDIUM','HARD']).optional(), points: z.number().min(0).max(100).optional() }).strict();
const quizSchema = z.object({ topicId: nullableUuid, courseId: nullableUuid, assignmentId: nullableUuid, title: z.string().trim().min(1).max(255), description: z.string().max(10000).optional().nullable(), quizType: z.enum(['PRACTICE','SELF_ASSESSMENT','COURSE_ASSIGNMENT','MOCK_EXAM']).optional(), status: z.enum(['DRAFT','PUBLISHED','ARCHIVED']).optional(), aiPolicy: z.enum(['AI_ALLOWED','AI_ALLOWED_WITH_DISCLOSURE','AI_LIMITED','AI_PROHIBITED']).optional(), generate: z.boolean().optional(), sourceIds: z.array(uuid).max(50).optional(), questionCount: z.number().int().min(1).max(50).optional(), questionTypes: z.array(z.enum(['MULTIPLE_CHOICE','TRUE_FALSE','SHORT_ANSWER','ISSUE_SPOTTING','CASE_ANALYSIS'])).optional(), difficulty: z.enum(['EASY','MEDIUM','HARD']).optional(), legalDomain: z.string().max(120).optional(), questions: z.array(questionSchema).max(100).optional() }).strict();
const attemptSubmit = z.object({ answers: z.array(z.object({ questionId: uuid, answer: z.any() }).strict()).max(200) }).strict();
const scenarioSchema = z.object({ workspaceId: uuid, title: z.string().trim().min(1).max(255), facts: z.string().min(1).max(100000), issues: z.array(z.any()).max(50).optional(), roles: z.array(z.enum(['CLAIMANT','RESPONDENT','JUDGE','ACADEMIC_OBSERVER'])).optional(), sourceIds: z.array(uuid).min(1).max(50), evidence: z.array(z.any()).max(100).optional(), rubric: json.optional(), status: z.enum(['DRAFT','ACTIVE','ARCHIVED']).optional() }).strict();
const projectSchema = z.object({ organizationId: nullableUuid, title: z.string().trim().min(1).max(255), abstract: z.string().max(20000).optional().nullable(), researchQuestion: z.string().max(20000).optional().nullable(), hypothesis: z.string().max(20000).optional().nullable(), methodology: z.string().max(20000).optional().nullable(), legalDomain: z.string().max(120).optional(), academicLevel: z.enum(['UNDERGRADUATE','GRADUATE','DOCTORAL','PROFESSIONAL','OTHER']).optional(), status: z.enum(['PLANNING','ACTIVE','ANALYSIS','WRITING','COMPLETED','ARCHIVED']).optional() }).strict();
const entrySchema = z.object({ entryType: z.enum(['LITERATURE_NOTE','CASE_NOTE','LEGISLATION_NOTE','METHOD_NOTE','FINDING','COUNTER_FINDING','LIMITATION']), title: z.string().trim().min(1).max(255), content: z.string().max(200000), legalSourceId: nullableUuid, chunkId: nullableUuid, tags: z.array(z.string().max(80)).max(50).optional() }).strict();
const codingSchema = z.object({ name: z.string().trim().min(1).max(255), description: z.string().max(10000).optional(), definition: json, status: z.enum(['DRAFT','ACTIVE','ARCHIVED']).optional() }).strict();
const codedItemSchema = z.object({ schemaId: uuid, legalSourceId: uuid, codedValues: json }).strict();
const courseSchema = z.object({ organizationId: nullableUuid, courseCode: z.string().max(80).optional(), title: z.string().trim().min(1).max(255), description: z.string().max(10000).optional(), term: z.string().max(120).optional(), legalDomain: z.string().max(120).optional(), academicLevel: z.enum(['UNDERGRADUATE','GRADUATE','DOCTORAL','PROFESSIONAL','OTHER']).optional(), enrollmentPolicy: z.enum(['INVITE_ONLY','ORGANIZATION','OPEN']).optional(), status: z.enum(['DRAFT','ACTIVE','ARCHIVED']).optional() }).strict();
const invitationSchema = z.object({ email: z.string().email().max(255), role: z.enum(['TEACHING_ASSISTANT','STUDENT','OBSERVER']).optional(), expiresInHours: z.number().int().min(1).max(168).optional() }).strict();
const assignmentSchema = z.object({ title: z.string().trim().min(1).max(255), description: z.string().max(20000).optional(), assignmentType: z.enum(['ESSAY','CASE_BRIEF','QUIZ','MOOT','RESEARCH']).optional(), dueAt: z.string().datetime().optional().nullable(), rubric: json.optional(), sourceCollectionId: nullableUuid, status: z.enum(['DRAFT','PUBLISHED','CLOSED','ARCHIVED']).optional(), aiPolicy: z.enum(['AI_ALLOWED','AI_ALLOWED_WITH_DISCLOSURE','AI_LIMITED','AI_PROHIBITED']).optional(), lateSubmissionPolicy: z.enum(['BLOCK','ALLOW','ALLOW_WITH_FLAG']).optional() }).strict();
const submissionSchema = z.object({ content: json, attachmentDocumentId: nullableUuid, aiDisclosure: json.optional() }).strict();
const gradeSchema = z.object({ grade: z.number().min(0).max(100), feedback: z.string().max(20000).optional().nullable() }).strict();
const collectionSchema = z.object({ title: z.string().trim().min(1).max(255), description: z.string().max(10000).optional(), collectionType: z.enum(['READING_LIST','CASEBOOK','BIBLIOGRAPHY','RESEARCH_CORPUS','CUSTOM']) }).strict();
const collectionItemSchema = z.object({ legalSourceId: nullableUuid, legalSourceChunkId: nullableUuid, externalSourceMetadata: json.optional(), title: z.string().trim().min(1).max(500), note: z.string().max(20000).optional(), sortOrder: z.number().int().min(0).optional() }).strict();
const annotationSchema = z.object({ legalSourceId: uuid, chunkId: nullableUuid, annotationType: z.enum(['HIGHLIGHT','COMMENT','QUESTION','ARGUMENT','COUNTER_ARGUMENT','METHOD_NOTE']), content: z.string().min(1).max(50000), startOffset: z.number().int().min(0).optional().nullable(), endOffset: z.number().int().min(0).optional().nullable(), tags: z.array(z.string().max(80)).max(50).optional(), visibility: z.enum(['PRIVATE','COURSE','WORKSPACE']).optional() }).strict();
const pageSchema = z.object({ limit: z.coerce.number().int().min(1).max(100).optional(), offset: z.coerce.number().int().min(0).optional(), sort: z.enum(['updated_at','created_at','title']).optional(), direction: z.enum(['asc','desc']).optional(), status: z.string().max(30).optional(), workspaceType: z.enum(['STUDENT','ACADEMIC','COURSE','RESEARCH_PROJECT']).optional() }).strict();
const annotationListSchema = z.object({ limit: z.coerce.number().int().min(1).max(100).optional(), offset: z.coerce.number().int().min(0).optional(), sort: z.enum(['created_at','updated_at']).optional(), direction: z.enum(['asc','desc']).optional(), sourceId: uuid.optional() }).strict();
const assignmentListSchema = z.object({ limit: z.coerce.number().int().min(1).max(100).optional(), offset: z.coerce.number().int().min(0).optional(), sort: z.enum(['due_at','created_at','title']).optional(), direction: z.enum(['asc','desc']).optional(), status: z.enum(['DRAFT','PUBLISHED','CLOSED','ARCHIVED']).optional() }).strict();

function handler(fn) { return async (req, res, next) => { try { await fn(req, res); } catch (error) { if (error instanceof z.ZodError) next(educationError(error.issues.map((issue) => `${issue.path.join('.') || 'request'}: ${issue.message}`).join('; '), 400, 'INVALID_EDUCATION_REQUEST')); else next(error); } }; }
async function context(req) { const value = await getAccessContext(req); if (!value) throw educationError('Authentication required.', 401, 'AUTH_REQUIRED'); return value; }
const services = () => getEducationServices();

exports.createWorkspace = handler(async (req,res) => res.status(201).json({ success:true,data:await services().workspaceService.create(workspaceCreate.parse(req.body),await context(req),{req}) }));
exports.listWorkspaces = handler(async (req,res) => res.json({ success:true,data:await services().workspaceService.list(await context(req),pageSchema.parse(req.query)) }));
exports.getWorkspace = handler(async (req,res) => res.json({ success:true,data:await services().workspaceService.get(uuid.parse(req.params.workspaceId),await context(req)) }));
exports.updateWorkspace = handler(async (req,res) => res.json({ success:true,data:await services().workspaceService.update(uuid.parse(req.params.workspaceId),workspacePatch.parse(req.body),await context(req)) }));
exports.deleteWorkspace = handler(async (req,res) => { await services().workspaceService.remove(uuid.parse(req.params.workspaceId),await context(req)); res.status(204).end(); });
exports.createTopic = handler(async (req,res) => res.status(201).json({ success:true,data:await services().workspaceService.createTopic(uuid.parse(req.params.workspaceId),topicSchema.parse(req.body),await context(req)) }));
exports.createNote = handler(async (req,res) => res.status(201).json({ success:true,data:await services().noteService.create(uuid.parse(req.params.workspaceId),noteCreate.parse(req.body),await context(req),{req}) }));
exports.getNote = handler(async (req,res) => res.json({ success:true,data:await services().noteService.get(uuid.parse(req.params.noteId),await context(req)) }));
exports.updateNote = handler(async (req,res) => res.json({ success:true,data:await services().noteService.update(uuid.parse(req.params.noteId),notePatch.parse(req.body),await context(req),{req}) }));
exports.suggestNote = handler(async (req,res) => res.status(201).json({ success:true,data:await services().noteService.suggest(uuid.parse(req.params.noteId),noteSuggestion.parse(req.body),await context(req)) }));
exports.createBrief = handler(async (req,res) => res.status(201).json({ success:true,data:await services().briefService.create(uuid.parse(req.params.workspaceId),briefCreate.parse(req.body),await context(req),{req}) }));
exports.generateBrief = handler(async (req,res) => res.json({ success:true,data:await services().briefService.generate(uuid.parse(req.params.briefId),await context(req),{req}) }));
exports.updateBrief = handler(async (req,res) => res.json({ success:true,data:await services().briefService.update(uuid.parse(req.params.briefId),briefPatch.parse(req.body),await context(req)) }));
exports.getBrief = handler(async (req,res) => res.json({ success:true,data:await services().briefService.get(uuid.parse(req.params.briefId),await context(req)) }));
exports.generateFlashcards = handler(async (req,res) => res.status(201).json({ success:true,data:await services().quizService.generateFlashcards(uuid.parse(req.params.workspaceId),flashcardSchema.parse(req.body),await context(req)) }));
exports.createQuiz = handler(async (req,res) => res.status(201).json({ success:true,data:await services().quizService.createQuiz(uuid.parse(req.params.workspaceId),quizSchema.parse(req.body),await context(req),{req}) }));
exports.createAttempt = handler(async (req,res) => res.status(201).json({ success:true,data:await services().quizService.createAttempt(uuid.parse(req.params.quizId),await context(req)) }));
exports.getQuiz = handler(async (req,res) => res.json({ success:true,data:await services().quizService.getQuiz(uuid.parse(req.params.quizId),await context(req)) }));
exports.submitAttempt = handler(async (req,res) => res.json({ success:true,data:await services().quizService.submitAttempt(uuid.parse(req.params.attemptId),attemptSubmit.parse(req.body),await context(req),{req}) }));
exports.createMootScenario = handler(async (req,res) => res.status(201).json({ success:true,data:await services().mootService.createScenario(scenarioSchema.parse(req.body),await context(req)) }));
exports.startMootSession = handler(async (req,res) => res.status(201).json({ success:true,data:await services().mootService.startSession(uuid.parse(req.params.scenarioId),z.object({selectedRole:z.enum(['CLAIMANT','RESPONDENT','JUDGE','ACADEMIC_OBSERVER'])}).strict().parse(req.body),await context(req),{req}) }));
exports.mootMessage = handler(async (req,res) => res.status(201).json({ success:true,data:await services().mootService.message(uuid.parse(req.params.sessionId),z.object({message:z.string().min(1).max(12000),assignmentId:nullableUuid}).strict().parse(req.body),await context(req)) }));
exports.createProject = handler(async (req,res) => res.status(201).json({ success:true,data:await services().researchService.createProject(projectSchema.parse(req.body),await context(req),{req}) }));
exports.getProject = handler(async (req,res) => res.json({ success:true,data:await services().researchService.getProject(uuid.parse(req.params.projectId),await context(req)) }));
exports.createEntry = handler(async (req,res) => res.status(201).json({ success:true,data:await services().researchService.createEntry(uuid.parse(req.params.projectId),entrySchema.parse(req.body),await context(req)) }));
exports.createCodingSchema = handler(async (req,res) => res.status(201).json({ success:true,data:await services().researchService.createCodingSchema(uuid.parse(req.params.projectId),codingSchema.parse(req.body),await context(req),{req}) }));
exports.codeSource = handler(async (req,res) => res.status(201).json({ success:true,data:await services().researchService.codeSource(uuid.parse(req.params.projectId),codedItemSchema.parse(req.body),await context(req),{req}) }));
exports.createCourse = handler(async (req,res) => res.status(201).json({ success:true,data:await services().courseService.create(courseSchema.parse(req.body),await context(req),{req}) }));
exports.inviteCourse = handler(async (req,res) => res.status(201).json({ success:true,data:await services().courseService.invite(uuid.parse(req.params.courseId),invitationSchema.parse(req.body),await context(req),{req}) }));
exports.acceptCourseInvitation = handler(async (req,res) => res.json({ success:true,data:await services().courseService.acceptInvitation(z.object({token:z.string().min(32).max(200)}).strict().parse(req.body).token,await context(req)) }));
exports.createAssignment = handler(async (req,res) => res.status(201).json({ success:true,data:await services().courseService.createAssignment(uuid.parse(req.params.courseId),assignmentSchema.parse(req.body),await context(req),{req}) }));
exports.listAssignments = handler(async (req,res) => res.json({ success:true,data:await services().courseService.listAssignments(uuid.parse(req.params.courseId),await context(req),assignmentListSchema.parse(req.query)) }));
exports.createSubmission = handler(async (req,res) => res.status(201).json({ success:true,data:await services().courseService.submit(uuid.parse(req.params.assignmentId),submissionSchema.parse(req.body),await context(req),{req}) }));
exports.getSubmission = handler(async (req,res) => res.json({ success:true,data:await services().courseService.getSubmission(uuid.parse(req.params.submissionId),await context(req)) }));
exports.gradeSubmission = handler(async (req,res) => res.json({ success:true,data:await services().courseService.grade(uuid.parse(req.params.submissionId),gradeSchema.parse(req.body),await context(req),{req}) }));
exports.createCollection = handler(async (req,res) => res.status(201).json({ success:true,data:await services().workspaceService.createCollection(uuid.parse(req.params.workspaceId),collectionSchema.parse(req.body),await context(req)) }));
exports.addCollectionItem = handler(async (req,res) => res.status(201).json({ success:true,data:await services().workspaceService.addCollectionItem(uuid.parse(req.params.collectionId),collectionItemSchema.parse(req.body),await context(req)) }));
exports.createAnnotation = handler(async (req,res) => res.status(201).json({ success:true,data:await services().annotationService.create(uuid.parse(req.params.workspaceId),annotationSchema.parse(req.body),await context(req),{req}) }));
exports.listAnnotations = handler(async (req,res) => res.json({ success:true,data:await services().annotationService.list(uuid.parse(req.params.workspaceId),await context(req),annotationListSchema.parse(req.query)) }));
exports.research = handler(async (req,res) => res.json({ success:true,data:await services().assistantService.research(uuid.parse(req.params.workspaceId),z.object({query:z.string().min(3).max(1000),effectiveAt:z.string().date().optional().nullable(),filters:json.optional(),idempotencyKey:z.string().max(255).optional()}).strict().parse(req.body),await context(req),{idempotencyKey:req.get('idempotency-key'),requestId:req.requestId,req}) }));

function sendExport(res, output) { res.setHeader('Content-Type',output.contentType); res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(output.filename)}`); res.send(output.buffer); }
exports.exportNote = handler(async (req,res) => sendExport(res,await services().exportService.exportNote(uuid.parse(req.params.noteId),z.enum(['DOCX','PDF']).parse(String(req.params.format).toUpperCase()),await context(req),{req})));
exports.exportProject = handler(async (req,res) => sendExport(res,await services().exportService.exportProject(uuid.parse(req.params.projectId),z.enum(['CSV','JSON','RIS','BIBTEX']).parse(String(req.query.format || 'JSON').toUpperCase()),await context(req),{req})));
