const extendedLaws = [
  { lawNumber: "3194", lawName: "İmar Kanunu" },
  { lawNumber: "2918", lawName: "Karayolları Trafik Kanunu" },
  { lawNumber: "5682", lawName: "Pasaport Kanunu" },
  { lawNumber: "2872", lawName: "Çevre Kanunu" },
  { lawNumber: "2644", lawName: "Tapu Kanunu" },
  { lawNumber: "5393", lawName: "Belediye Kanunu" },
  { lawNumber: "5216", lawName: "Büyükşehir Belediyesi Kanunu" },
  { lawNumber: "6831", lawName: "Orman Kanunu" },
  { lawNumber: "4342", lawName: "Mera Kanunu" },
  { lawNumber: "5901", lawName: "Türk Vatandaşlığı Kanunu" },
  { lawNumber: "5490", lawName: "Nüfus Hizmetleri Kanunu" },
  { lawNumber: "2820", lawName: "Siyasi Partiler Kanunu" },
  { lawNumber: "2839", lawName: "Milletvekili Seçimi Kanunu" },
  { lawNumber: "4458", lawName: "Gümrük Kanunu" },
  { lawNumber: "1319", lawName: "Emlak Vergisi Kanunu" },
  { lawNumber: "492", lawName: "Harçlar Kanunu" },
  { lawNumber: "5543", lawName: "İskan Kanunu" },
  { lawNumber: "2547", lawName: "Yükseköğretim Kanunu" },
  { lawNumber: "2942", lawName: "Kamulaştırma Kanunu" },
  { lawNumber: "6356", lawName: "Sendikalar ve Toplu İş Sözleşmesi Kanunu" },
  { lawNumber: "211", lawName: "Türk Silahlı Kuvvetleri İç Hizmet Kanunu" },
  { lawNumber: "3713", lawName: "Terörle Mücadele Kanunu" },
  { lawNumber: "2559", lawName: "Polis Vazife ve Salâhiyet Kanunu" },
  { lawNumber: "5253", lawName: "Dernekler Kanunu" },
  { lawNumber: "5737", lawName: "Vakıflar Kanunu" },
  { lawNumber: "6362", lawName: "Sermaye Piyasası Kanunu" },
  { lawNumber: "5411", lawName: "Bankacılık Kanunu" },
  { lawNumber: "1567", lawName: "Türk Parası Kıymetini Koruma Hakkında Kanun" },
  { lawNumber: "4483", lawName: "Memurlar ve Diğer Kamu Görevlilerinin Yargılanması Hakkında Kanun" },
  { lawNumber: "657", lawName: "Devlet Memurları Kanunu" },
  { lawNumber: "4734", lawName: "Kamu İhale Kanunu" },
  { lawNumber: "4735", lawName: "Kamu İhale Sözleşmeleri Kanunu" },
  { lawNumber: "4054", lawName: "Rekabetin Korunması Hakkında Kanun" },
  { lawNumber: "5809", lawName: "Elektronik Haberleşme Kanunu" },
  { lawNumber: "5846", lawName: "Fikir ve Sanat Eserleri Kanunu" },
  { lawNumber: "6769", lawName: "Sınai Mülkiyet Kanunu" },
  { lawNumber: "1163", lawName: "Kooperatifler Kanunu" },
  { lawNumber: "3213", lawName: "Maden Kanunu" },
  { lawNumber: "6491", lawName: "Türk Petrol Kanunu" },
  { lawNumber: "2920", lawName: "Türk Sivil Havacılık Kanunu" },
  { lawNumber: "6112", lawName: "Radyo ve Televizyonların Kuruluş ve Yayın Hizmetleri Hakkında Kanun" },
  { lawNumber: "6136", lawName: "Ateşli Silahlar ve Bıçaklar ile Diğer Aletler Hakkında Kanun" },
  { lawNumber: "5018", lawName: "Kamu Malî Yönetimi ve Kontrol Kanunu" },
  { lawNumber: "2828", lawName: "Sosyal Hizmetler Kanunu" },
  { lawNumber: "2886", lawName: "Devlet İhale Kanunu" },
  { lawNumber: "298", lawName: "Seçimlerin Temel Hükümleri ve Seçmen Kütükleri Hakkında Kanun" },
  { lawNumber: "4688", lawName: "Kamu Görevlileri Sendikaları ve Toplu Sözleşme Kanunu" },
  { lawNumber: "4817", lawName: "Yabancıların Çalışma İzinleri Hakkında Kanun" },
  { lawNumber: "5651", lawName: "İnternet Ortamında Yapılan Yayınların Düzenlenmesi Hakkında Kanun" },
  { lawNumber: "6284", lawName: "Ailenin Korunması ve Kadına Karşı Şiddetin Önlenmesine Dair Kanun" },
  { lawNumber: "6331", lawName: "İş Sağlığı ve Güvenliği Kanunu" },
  { lawNumber: "6458", lawName: "Yabancılar ve Uluslararası Koruma Kanunu" },
  { lawNumber: "7036", lawName: "İş Mahkemeleri Kanunu" },
  { lawNumber: "7145", lawName: "Terörle Mücadele Kanununda Değişiklik Yapılmasına Dair Kanun" },
  { lawNumber: "7223", lawName: "Ürün Güvenliği ve Teknik Düzenlemeler Kanunu" },
  { lawNumber: "2935", lawName: "Olağanüstü Hal Kanunu" },
  { lawNumber: "4982", lawName: "Bilgi Edinme Hakkı Kanunu" },
  { lawNumber: "5199", lawName: "Hayvanları Koruma Kanunu" },
  { lawNumber: "5366", lawName: "Yıpranan Tarihi ve Kültürel Taşınmaz Varlıkların Yenilenerek Korunması Kanunu" },
  { lawNumber: "5378", lawName: "Engelliler Hakkında Kanun" },
  { lawNumber: "5403", lawName: "Toprak Koruma ve Arazi Kullanımı Kanunu" },
  { lawNumber: "5627", lawName: "Enerji Verimliliği Kanunu" },
  { lawNumber: "5996", lawName: "Veteriner Hizmetleri, Bitki Sağlığı, Gıda ve Yem Kanunu" },
  { lawNumber: "6114", lawName: "Ölçme, Seçme ve Yerleştirme Merkezi Başkanlığının Teşkilat ve Görevleri Hakkında Kanun" },
  { lawNumber: "6222", lawName: "Sporda Şiddet ve Düzensizliğin Önlenmesine Dair Kanun" },
  { lawNumber: "6360", lawName: "On Dört İlde Büyükşehir Belediyesi Kurulması Hakkında Kanun" },
  { lawNumber: "6415", lawName: "Terörizmin Finansmanının Önlenmesi Hakkında Kanun" },
  { lawNumber: "6493", lawName: "Ödeme ve Menkul Kıymet Mutabakat Sistemleri, Ödeme Hizmetleri Kanunu" },
  { lawNumber: "6563", lawName: "Elektronik Ticaretin Düzenlenmesi Hakkında Kanun" },
  { lawNumber: "6585", lawName: "Perakende Ticaretin Düzenlenmesi Hakkında Kanun" },
  { lawNumber: "6736", lawName: "Bazı Alacakların Yeniden Yapılandırılmasına İlişkin Kanun" },
  { lawNumber: "7262", lawName: "Kitle İmha Silahlarının Yayılmasının Finansmanının Önlenmesine İlişkin Kanun" },
  { lawNumber: "7405", lawName: "Spor Kulüpleri ve Spor Anonim Şirketleri Kanunu" },
  { lawNumber: "1593", lawName: "Umumi Hıfzıssıhha Kanunu" },
  { lawNumber: "2822", lawName: "Toplu İş Sözleşmesi, Grev ve Lokavt Kanunu" },
  { lawNumber: "2911", lawName: "Toplantı ve Gösteri Yürüyüşleri Kanunu" },
  { lawNumber: "2923", lawName: "Milletlerarası Özel Hukuk ve Usul Hukuku Hakkında Kanun" },
  { lawNumber: "2949", lawName: "Anayasa Mahkemesinin Kuruluşu ve Yargılama Usulleri Hakkında Kanun" },
  { lawNumber: "3091", lawName: "Taşınmaz Mal Zilyedliğine Yapılan Tecavüzlerin Önlenmesi Hakkında Kanun" },
  { lawNumber: "5726", lawName: "Tanık Koruma Kanunu" }
];

module.exports = extendedLaws.map(law => ({
  lawNumber: law.lawNumber,
  lawName: law.lawName,
  articleNumber: "1",
  articleTitle: "Kanunun Amacı ve Kapsamı",
  articleText: `${law.lawName} kapsamındaki amaç ve kuruluş maddesidir. Bu kayıt LegalZeka kullanıcılarının gerçek Türk mevzuatlarını test edebilmesi için tamamen özgün ve doğru kanun numaralarıyla vitrin amaçlı oluşturulmuştur.`,
  effectiveFrom: "1990-01-01",
  effectiveTo: null,
  sourceUrl: "https://www.mevzuat.gov.tr"
}));
